// This file is auto-generated by Supabase.
// You can regenerate it with: npx supabase gen types typescript --project-id <your-project-id> > lib/database.types.ts
// For this example, I'll provide a simplified version.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          has_onboarded: boolean | null
        }
        // ... other fields
      }
      teams: {
        Row: {
          id: string
          user_id: string
          name: string
          whitelisted_phone_numbers: string[] | null
          sms_code: string
          created_at: string
        }
        Insert: {
          user_id: string
          name: string
          whitelisted_phone_numbers?: string[] | null
          sms_code: string
        }
        // ... other fields
      }
      seasons: {
        Row: {
          id: string
          team_id: string
          name: string
          created_at: string
        }
        // ... other fields
      }
      players: {
        Row: {
          id: string
          team_id: string
          name: string
          created_at: string
        }
        Insert: {
          team_id: string
          name: string
        }
        // ... other fields
      }
      results: {
        Row: {
          id: string
          player_id: string
          season_id: string
          game_date: string
          stats: Json | null
          created_at: string
        }
        // ... other fields
      }
      games: {
        Row: {
          id: string
          team_id: string
          season_id: string
          game_date: string
          created_at: string
          source: string
        }
        // ... other fields
      }
    }
    // ... other database objects
  }
}
